name: build-push-image
run-name: Build and push an image
on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: "git ref to build"
        required: true
        default: origin/main
        type: string


jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: "${{ inputs.git_ref }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          name: container-builder
      - name: buildx info
        run: |
          docker buildx ls
      - name: Build and push
        run: |
          set -e -u -o pipefail && \
          tag=compactor-workaround-$(git rev-parse --short HEAD) && \
          echo 1>&2 "Building tag ${tag}" && \
          docker buildx use container-builder && \
          DOCKER_BUILDKIT=0 docker buildx build \
            --platform=linux/amd64,linux/arm64 \
            --build-arg GO_VERSION=1.25.3 \
            --build-arg BUILD_IMAGE=grafana/loki-build-image:0.34.6 \
            --build-arg IMAGE_TAG="${tag}" \
            --label org.opencontainers.image.source=http://github.com/ringerc/loki \
            --label org.opencontainers.image.description="A temporary Loki fork for working around a Compactor bug with Azure Lakehouse Storage (Azure Blob Storage gen2)" \
            --label org.opencontainers.image.licenses="AGPL" \
            -t "ghcr.io/ringerc/loki:${tag}" \
            -f cmd/loki/Dockerfile . &&
          docker push "ghcr.io/ringerc/loki:${tag}"
